chinese:
  - asian
thai:
  - asian
sushi:
  - asian
korean:
  - asian
noodle:
  - asian
vietnamese:
  - asian
cantonese:
  - chinese
  - asian
szechuan:
  - chinese
  - asian
hunan:
  - chinese
  - asian
japanese:
  - asian
pizza:
  - italian
pancake:
  - breakfast
bagel:
  - breakfast
cafe:
  - coffee
coffee shop:
  - cafe
coffee:
  - cafe
donut:
  - breakfast
  - doughnut
doughnut:
  - breakfast
  - donut
grave yard:
  - cemetery
peak:
  - mountain
townhall:
  - town hall
cuisine:
  - food
  - restaurant
  - dining
restaurant:
  - food
  - dining
aerodrome:
  - airport
fuel:
  - gas
  - gas station
pharmacy:
  - drug store
  - druggist
  - chemist
shop:
  - store
alcohol:
  - liquor
theater:
  - theatre
theatre:
  - theater
toilets:
  - bathroom
